Feature testimonials
Anastassia2312/team-22-project pull request #1
Opened 2023-09-30 18:05 UTC by Go088

2023-09-30 19:07 UTC, Anastassia2312 requested changes

2023-09-30 19:07 UTC, Anastassia2312 commented on src/css/testimonials.css
> +        display: flex;
Треба прибрати властивість

2023-09-30 19:07 UTC, Anastassia2312 commented on src/css/testimonials.css
> +        justify-content: center;
Треба прибрати властивість

2023-09-30 19:07 UTC, Anastassia2312 commented on src/css/testimonials.css
> +        align-items: center;
Треба прибрати властивість

2023-09-30 20:10 UTC, Go088 commented on src/css/testimonials.css
> +        display: flex;
Виправлено

2023-09-30 20:10 UTC, Go088 commented on src/css/testimonials.css
> +        justify-content: center;
Виправлено

2023-09-30 20:11 UTC, Go088 commented on src/css/testimonials.css
> +        align-items: center;
Виправлено

2023-10-01 04:53 UTC, Anastassia2312 approved these changes

2023-10-01 04:53 UTC, merged